from distutils.sysconfig import get_config_vars
from numpy.distutils.misc_util import Configuration
from Cython.Build import cythonize
import numpy
import os


def strict_prototypes_workaround():
    # Workaround to remove '-Wstrict-prototypes' from compiler invocation
    (opt,) = get_config_vars('OPT')
    os.environ['OPT'] = " ".join(
        flag for flag in opt.split() if flag != '-Wstrict-prototypes'
    )


def cython_path(filename):
    if "setup.pyc" in __file__:
        return __file__.replace("setup.pyc", filename)
    else:
        return __file__.replace("setup.py", filename)


def configuration(parent_package='', top_path=None):
    strict_prototypes_workaround()

    config = Configuration("svm", parent_package, top_path)
    cythonize(cython_path("_svm.pyx"), language="c++")
    config.add_extension(
        '_svm',
        sources=["_svm.cpp"],  # Generated by cythonize
        include_dirs=[".", numpy.get_include()],
        define_macros=[("NDEBUG",)],
        extra_compile_args=[
            "-O3",
            # disable warnings caused by Cython using the deprecated
            # NumPy C-API
            "-Wno-cpp", "-Wno-unused-function",
        ])
    return config